-- MySQL Script generated by MySQL Workbench
-- Wed 26 Apr 2017 03:34:01 PM +0530
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema purelightDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema purelightDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `purelightDB` DEFAULT CHARACTER SET utf8 ;
USE `purelightDB` ;

-- -----------------------------------------------------
-- Table `purelightDB`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purelightDB`.`Role` (
  `roleId` INT NOT NULL AUTO_INCREMENT,
  `UserRolecol` VARCHAR(45) NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purelightDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purelightDB`.`User` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Role_Role Id` INT NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_User_Role1_idx` (`Role_Role Id` ASC),
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_Role Id`)
    REFERENCES `purelightDB`.`Role` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purelightDB`.`Healer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purelightDB`.`Healer` (
  `healerId` INT NOT NULL AUTO_INCREMENT,
  `HealerDiscription` VARCHAR(1000) NULL,
  `HealerImageUrl` VARCHAR(200) NULL,
  `HealerName` VARCHAR(200) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`healerId`),
  INDEX `fk_Healer_User_idx` (`User_id` ASC),
  CONSTRAINT `fk_Healer_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `purelightDB`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purelightDB`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purelightDB`.`Customer` (
  `customerId` INT NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(45) NULL,
  `CustomerEmail` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `BankDetail` VARCHAR(45) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`customerId`),
  INDEX `fk_Customer_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Customer_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `purelightDB`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purelightDB`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purelightDB`.`Admin` (
  `adminId` INT NOT NULL AUTO_INCREMENT,
  `AdminDiscription` VARCHAR(1000) NULL,
  `AdminImageUrl` VARCHAR(200) NULL,
  `AdminWebUrl` VARCHAR(200) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`adminId`),
  INDEX `fk_Healer_User_idx` (`User_id` ASC),
  CONSTRAINT `fk_Healer_User0`
    FOREIGN KEY (`User_id`)
    REFERENCES `purelightDB`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purelightDB`.`Offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purelightDB`.`Offers` (
  `offerId` INT NOT NULL,
  `OfferName` VARCHAR(45) NULL,
  `Discount` VARCHAR(45) NULL,
  PRIMARY KEY (`offerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purelightDB`.`Media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purelightDB`.`Media` (
  `MediaId` INT NOT NULL AUTO_INCREMENT,
  `Healer_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `teaserDescription` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `howToUse` VARCHAR(45) NULL,
  `cautions` VARCHAR(45) NULL,
  `Offer_id` INT NULL,
  PRIMARY KEY (`MediaId`),
  INDEX `fk_Media_Healer1_idx` (`Healer_id` ASC),
  INDEX `fk_Media_Offer1_idx` (`Offer_id` ASC),
  CONSTRAINT `fk_Media_Healer1`
    FOREIGN KEY (`Healer_id`)
    REFERENCES `purelightDB`.`Healer` (`healerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Media_Offer1`
    FOREIGN KEY (`Offer_id`)
    REFERENCES `purelightDB`.`Offers` (`offerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purelightDB`.`Track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purelightDB`.`Track` (
  `trackId` INT NOT NULL,
  `Media_MediaId` INT NOT NULL,
  `trackName` VARCHAR(45) NULL,
  `trackurl` VARCHAR(45) NULL,
  `duration` VARCHAR(45) NULL,
  PRIMARY KEY (`trackId`),
  INDEX `fk_Track_Media1_idx` (`Media_MediaId` ASC),
  CONSTRAINT `fk_Track_Media1`
    FOREIGN KEY (`Media_MediaId`)
    REFERENCES `purelightDB`.`Media` (`MediaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purelightDB`.`DownloadDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purelightDB`.`DownloadDetail` (
  `Media_MediaId` INT NOT NULL,
  `Download_count` INT(11) NULL,
  `Search_cont` INT(11) NULL,
  PRIMARY KEY (`Media_MediaId`),
  CONSTRAINT `fk_Downloads_Media1`
    FOREIGN KEY (`Media_MediaId`)
    REFERENCES `purelightDB`.`Media` (`MediaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purelightDB`.`PurchaseDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purelightDB`.`PurchaseDetail` (
  `purchaseId` INT NOT NULL AUTO_INCREMENT,
  `Media_MediaId` INT NOT NULL,
  `Customer_id` INT NOT NULL,
  `Cost` MEDIUMTEXT NULL,
  PRIMARY KEY (`purchaseId`),
  INDEX `fk_PurchaseDetail_Media1_idx` (`Media_MediaId` ASC),
  INDEX `fk_PurchaseDetail_Customer1_idx` (`Customer_id` ASC),
  CONSTRAINT `fk_PurchaseDetail_Media1`
    FOREIGN KEY (`Media_MediaId`)
    REFERENCES `purelightDB`.`Media` (`MediaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PurchaseDetail_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `purelightDB`.`Customer` (`customerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;