# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.AutoField(db_column='adminId', primary_key=True, serialize=False)),
                ('admindiscription', models.CharField(blank=True, db_column='AdminDiscription', max_length=1000, null=True)),
                ('adminimageurl', models.CharField(blank=True, db_column='AdminImageUrl', max_length=200, null=True)),
                ('adminweburl', models.CharField(blank=True, db_column='AdminWebUrl', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(db_column='customerId', primary_key=True, serialize=False)),
                ('customername', models.CharField(blank=True, db_column='CustomerName', max_length=45, null=True)),
                ('customeremail', models.CharField(blank=True, db_column='CustomerEmail', max_length=45, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=45, null=True)),
                ('bankdetail', models.CharField(blank=True, db_column='BankDetail', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healer',
            fields=[
                ('healerid', models.AutoField(db_column='healerId', primary_key=True, serialize=False)),
                ('healerdiscription', models.CharField(blank=True, db_column='HealerDiscription', max_length=1000, null=True)),
                ('healerimageurl', models.CharField(blank=True, db_column='HealerImageUrl', max_length=200, null=True)),
                ('healercol', models.CharField(blank=True, db_column='Healercol', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Healer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('mediaid', models.AutoField(db_column='MediaId', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('teaserdescription', models.CharField(blank=True, db_column='teaserDescription', max_length=45, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('url', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('howtouse', models.CharField(blank=True, db_column='howToUse', max_length=45, null=True)),
                ('cautions', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offerid', models.IntegerField(db_column='offerId', primary_key=True, serialize=False)),
                ('offername', models.CharField(blank=True, db_column='OfferName', max_length=45, null=True)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchasedetail',
            fields=[
                ('purchaseid', models.AutoField(db_column='purchaseId', primary_key=True, serialize=False)),
                ('cost', models.TextField(blank=True, db_column='Cost', null=True)),
            ],
            options={
                'db_table': 'PurchaseDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.AutoField(db_column='roleId', primary_key=True, serialize=False)),
                ('userrolecol', models.CharField(blank=True, db_column='UserRolecol', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('trackid', models.IntegerField(db_column='trackId', primary_key=True, serialize=False)),
                ('trackname', models.CharField(blank=True, db_column='trackName', max_length=45, null=True)),
                ('trackurl', models.CharField(blank=True, max_length=45, null=True)),
                ('duration', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Track',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=45, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Downloaddetail',
            fields=[
                ('media_mediaid', models.ForeignKey(db_column='Media_MediaId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='purelight.Media')),
                ('download_count', models.IntegerField(blank=True, db_column='Download_count', null=True)),
                ('search_count', models.IntegerField(blank=True, db_column='Search_cont', null=True)),
            ],
            options={
                'db_table': 'DownloadDetail',
                'managed': False,
            },
        ),
    ]
